version: '3.8'

services:
  magic-inventory-frontend:
    image: ghcr.io/victor-aranda-code/magic-inventory-frontend:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - magic-inventory-backend
    environment:
      - BACKEND_URL=https://magic-inventory-backend:8443
    volumes:
      - ./certs:/etc/nginx/ssl:ro

  magic-inventory-backend:
    image: ghcr.io/victor-aranda-code/magic-inventory-backend:latest
    restart: always
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8443
      - SSL_KEY_STORE_PATH=/certs/keystore.p12
      - SSL_KEY_STORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - SSL_KEY_ALIAS=magic-inventory
      # The following variables should be defined in the Azure Web App Application Settings
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - AZURE_OPENAI_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./certs:/certs:ro

