name: Manual Multi-Container Deployment

on:
  workflow_dispatch:
    description: 'Manual trigger to deploy the latest frontend and backend images to Azure Web App'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Set K8s Context'
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: 'Deploy to AKS'
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            deployment.yml
          images: |
            ghcr.io/victor-aranda-code/magic-inventory-backend:latest
            ghcr.io/victor-aranda-code/magic-inventory-frontend:latest
